title: Python Lab
email: shagirov(at)nus.edu.sg
description: Python workshops and tutorials
baseurl: "/pythonlab"
url: "https://mshagirov.github.io/pythonlab"

github_username:  mshagirov

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tabs

collections:
  01-introduction:
    output: true
  02-lab-env-setup:
    output: true

exclude:
  - docs/
  - 99-exercise/
  - build.sh
  - dev.sh
  - README.md
